cargo-features = ["codegen-backend"]

[package]
name = "{{project-name}}"
authors = ["{{authors}}"]
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.19"
bevy_asset_loader = { version = "0.27", features = ["2d"] }
rand = { version = "0.10", features = [] }
rand_chacha = "0.10"
getrandom = { version = "0.4", features = ["wasm_js"] }
web-time = "1.1"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy_remote = { version = "0.19", optional = true }

[features]
debug = ["dep:bevy_remote", "bevy/dev"]
default = ["debug"]

[profile.dev]
opt-level = 1
codegen-backend = "cranelift"

[profile.dev.package."*"]
opt-level = 3
codegen-backend = "llvm"

[profile.release]
codegen-units = 1
lto = "thin"

[profile.web]
inherits = "release"
opt-level = "s"
strip = "debuginfo"
